<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LXG-PC" name="127.0.0.1:62001" tests="2" failures="1" timestamp="25 Dec 2016 07:47:16 GMT" time="89.829" errors="0">
  <testcase name="t001_login" time="19.738" classname="cn.crazy.appium.testcases.ZhiHuTest"/>
  <testcase name="t001_login" time="22.987" classname="cn.crazy.appium.testcases.ZhiHuTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at cn.crazy.appium.testcases.ZhiHuTest.t001_login(ZhiHuTest.java:65)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- t001_login -->
</testsuite> <!-- 127.0.0.1:62001 -->
