<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dmall-zhang-PC" name="da926816" tests="1" failures="0" timestamp="27 Dec 2016 07:36:31 GMT" time="4.308" errors="0">
  <testcase name="@AfterClass afterClass" time="0.0" classname="cn.crazy.appium.testcases.ZhiHuTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at cn.crazy.appium.testcases.ZhiHuTest.afterClass(ZhiHuTest.java:147)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass afterClass -->
  <testcase name="t001_login" time="0.0" classname="cn.crazy.appium.testcases.ZhiHuTest">
    <skipped/>
  </testcase> <!-- t001_login -->
</testsuite> <!-- da926816 -->
