<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LXG-PC" name="Test2" tests="1" failures="1" timestamp="27 Aug 2016 09:23:33 GMT" time="97.66" errors="0">
  <testcase name="login" time="53.675" classname="cn.crazy.appium.network.study.Test0716">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at cn.crazy.appium.network.study.Test0716.login(Test0716.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test2 -->
